### ISSUE TITLE
Misleading statement

### ISSUE THREAD

**Issue by WebReflection** [Rich-Harris/dom-monster#1]
> His vanilla DOM implementation is actually slower 

That's just your opinion, 'cause your library performed always worst than DOM and paperclip [in all tested devices](http://webreflection.blogspot.co.uk/2015/04/is-anyone-testing-on-mobile.html). Maybe your Chrome goes 60FPS with Reactive, but it does not matter if everything else goes slow.

Please drop that sentence or modify it, thank you.

**Comment by WebReflection** [comment]
More evidence [here](https://www.youtube.com/watch?v=ueWsYddNkqE), webOS is OKish and crappy anyway, check FirefoxOS, check carefully and tell me again my vanilla DOM is slower.

**Comment by Rich-Harris** [comment]
Fine, I'll change the wording when you change the title of your post from 'The DOM Is NOT Slow, Your Abstraction Is', to 'The DOM Is NOT Slow, Your Abstraction Might Be, Depending On Which One You Use'.

Just kidding! I've changed the wording to make the existing caveat clearer. 

> That's just your opinion

No, it was based on an [FPS meter](http://ricardocabello.com/blog/post/707). Chrome is the most widely-used browser according to StatCounter, so the results there are significant. But I take your point that we should be testing on lower-powered devices.

**Comment by WebReflection** [comment]
Nobody ever had a problem in Chrome, I start believing you've missed entirely the point of my later posts.

**Comment by WebReflection** [comment]
>  those tools are often unnecessary and often cause performance problems.

I've never stated that anywhere. My entire article is about developers that blindly believes whatever hyped FUD is around. If a developer is doing it wrong, regardless the usage or not of any framework at all, it's completely pointless to point the finger and say that DOM is slow, HTML5 sucks, and all this pile of poo I've been reading or hearing here and there.

There are so many frameworks promoters that keep saying how much they solved in terms of performance, and how better is is to completely couple yur development with their framework.

**NO**, this is wrong, misleading, it's marketing, and while I understand the marketing behind, I don't agree that's the real state of Web development.

React is the slowest in all my tests ... no wonders they are now pushing for native, instead of going faster we risk to not go at all or go slower than anything else.

We are in a Mobile era, we should stop NOW to test stuff only on Chrome for Desktop, on 4GB minimum amount of RAM machines, and 2 CPUs at 3GHz.

Or if that's the only target we care, why are we wasting even time? Nobody ever had these problems in a reasonable code base about performance in here, I've worked on projects that requires crazy amount of constant updates and on Desktop these work just fine.

Developers think that if it's fast on their super-computer it's going to be fast on mobile too: this is FALSE, you've seen the bench and confirmed indeed you never tried there.

Accordingly, do developers need these abstractions? Do they know what they are missing?

Your library solves so many things I didn't need it and yet I've created something that performs as well or better over all devices I could try. Why would I use your library? To make already fast Chrome, faster?

Do I care at all? Is that why the Web suck? Chrome doesn't update 1000 cells 30FPS nobody can even read the value?

Please try to understand what I am writing, and stop the campaign against vanilla DOM usage, let developers understand instead why they should use your libarry, and leave the DOM alone.

It's thanks to the DOM your library can exist in the first place, so please be reasonable and don't mislead an already very confused field like the Web is.

Thank you

**Comment by Rich-Harris** [comment]
> React is the slowest in all my tests ... no wonders they are now pushing for native, instead of going faster we risk to not go at all or go slower than anything else.

Is React Native the thing that motivated the original post? If so we might agree more than I thought... though I really wish you'd said so in the first place because I honestly thought you were attacking a straw man! I've never heard framework authors claim that they could somehow cheat and beat the DOM, only that poorly written code written to a framework will often beat poorly written code written against vanilla DOM (you know, people constantly requerying or abusing `innerHTML`, that kind of thing). Perhaps the marketing is a little hype-y in some cases - I'm sure a lot of people _are_ mistaken about the performance they can expect from React.

Having said that, the React team have publicly said (sorry, I don't have a link to hand) that they really regretted having to do React Native, and that they'd have rather have stuck to the web. But React Native allows developers to do some pretty great stuff that's basically impossible with the DOM (e.g. layout and image decoding off the main thread), so they _do_ have a point. If their work means that one day we get similar capabilities on the web, then personally I'm all for it! 

> Why would I use your library?

Because, as you rightly pointed out, dbmonster is a contrived test. It doesn't resemble a real-world app, and it's not designed to. Writing a real-world app with vanilla DOM is the road to madness. (I suspect this is the point where we disagree :) You know that `append(where, what)` function? You'd end up with lots of similar functions for basic DOM manipulation, and then you'd probably have some functions for data validation, and routing, and persistence, and AJAX... and before you know it you've built a framework! All those functions are examples of abstractions. (You might say 'indirection' or 'DRY' instead of 'abstraction', but I've never heard anyone convincingly delineate between those concepts - the boundary is fuzzy at best.)

When you use a library or a framework, you get all that functionality - and a community-derived set of idioms - with documentation and tests. But you know all that, because you're a library author!

> We are in a Mobile era, we should stop NOW to test stuff only on Chrome for Desktop, on 4GB minimum amount of RAM machines, and 2 CPUs at 3GHz.

You're right. One of the things I've been thinking about is how to do automated perf testing for Ractive on slower devices. Because we're a small independent team with no funding, we don't have the budget for a device lab, so it's hard. But we do need to find a way.

**Comment by WebReflection** [comment]
> Writing a real-world app with vanilla DOM is the road to madness. (I suspect this is the point where we disagree :)

vanilla [here](m.here.com/), [here](https://mobile.twitter.com), and once upon a time [here](https://m.facebook.com): I've personally worked in all those teams for the last 6 years.

So you are right, we disagree.

> You know that append(where, what) function? You'd end up with lots of similar functions for basic DOM manipulation

No, if you were updated with latest DOM you'd know that [append is native](https://dom.spec.whatwg.org/#parentnode) together with prepend.

I didn't use `append` because I would have needed [my dom4 poly](https://github.com/WebReflection/dom4) in and I thought that would have mislead the purpose of the benchmark.

Testing stuff on mobile does not require a Lab, if you have a desk, you are already good to go.

You need one cheap device that is not your latest phone, and a reachable IP address in the office/home intranet. You connect through that IP and you test whatever you want.

For Android automated tests there are tools, but I've actually written a simple one that runs every-bloody-where, it's called [testardo](https://github.com/WebReflection/testardo#testardo)

It's not perfect, but it can give you some automation too (check the video if you have time)
